version: "3"
services:
  react-app:
    image: react
    build:
      context: react_front
      target: production
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:80"
    networks:
      - react-express
    
  api-server:
    image: express
    build:
      context: ExpressBackend
      target: build
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - react-express

networks:
  react-express:
    driver: bridge

      