version: "3"
services:

  api-server:
    build: ./ExpressBackend
    volumes:
      - logs:/usr/src/app
    image: express
    ports:
      - "5000:5000"
    networks:
      - react-express

  react-app:
    build: ./react_front
    image: react
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - react-express
    depends_on:
      - api-server

volumes:
  logs:
# on windows, go to this file path to send logs \\wsl$\docker-desktop-data\data\docker\volumes\reacttest_logs\_data\watch-folder

networks:
  react-express:
    driver: bridge

# in the react_front, change the localhost in the proxy to "http://api-server:5000" from   "proxy": "http://localhost:5000",


      