version: "3"
services:
  api-server:
    build: 
      context: ./ExpressBackend
      args:
        HOST_IP_ADDRESS : ${IP_ADDRESS}
    volumes:
      - "${FOLDER_PATH}:/usr/src/app/watch-folder"
    image: express
    ports:
      - "5000:5000"
    networks:
      - react-express

  react-app:
    build:
      context: ./react_front
      args:
        REACT_APP_HOST_IP_ADDRESS: ${IP_ADDRESS}
    image: react
    stdin_open: true
    volumes:
      - ./react_front/filterui.crt:/etc/react_front/filterui.crt # New Line!
      - ./react_front/filterui.key:/etc/react_front/filterui.key # New Line!
    ports:
      - "3000:80"
      - "3001:443"
    networks:
      - react-express
    depends_on:
      - api-server

# volumes:
#   mydata:

# on windows, go to this file path to send logs \\wsl$\docker-desktop-data\data\docker\volumes\reacttest_logs\_data\watch-folder
# on centos, /var/lib/docker/volumes/reacttest_logs/_data/watch-folder/
networks:
  react-express:
    driver: bridge

# in the react_front, change the localhost in the proxy to "http://api-server:5000" from   "proxy": "http://localhost:5000",


      